import json
import os

INPUT_FILE = "oncology_final_reports.json"
OUTPUT_HTML = "oncology_dashboard.html"

def json_to_html():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found!")
        return

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        reports = json.load(f)

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Oncology AI Multi-Agent Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ background-color: #f4f7f6; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }}
            .card {{ border: none; box-shadow: 0 4px 12px rgba(0,0,0,0.1); margin-bottom: 30px; }}
            .card-header {{ background-color: #2c3e50; color: white; font-weight: bold; }}
            .section-title {{ border-left: 5px solid #3498db; padding-left: 10px; margin: 20px 0 10px; color: #2c3e50; }}
            .badge-corrected {{ background-color: #e67e22; }}
            pre {{ background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1px solid #dee2e6; white-space: pre-wrap; }}
            .assessment-text {{ font-style: italic; color: #34495e; line-height: 1.6; }}
            .plan-box {{ background-color: #e8f4fd; border-left: 5px solid #2980b9; padding: 15px; }}
            .sticky-top {{ background: rgba(255,255,255,0.9); backdrop-filter: blur(5px); padding: 10px 0; border-bottom: 1px solid #ddd; }}
        </style>
    </head>
    <body>
        <div class="sticky-top">
            <div class="container d-flex justify-content-between align-items-center">
                <h2 class="mb-0">🩺 Oncology Agent Dashboard</h2>
                <span class="badge bg-primary">Total Samples: {len(reports)}</span>
            </div>
        </div>

        <div class="container mt-4">
    """

    for report in reports:
        sid = report.get("sample_id", "N/A")
        corrected_badge = '<span class="badge badge-corrected">Critic Corrected</span>' if report.get("was_corrected") else ""
        
        # 格式化 JSON 数据
        struct_data = json.dumps(report.get("structured_data", {}), indent=2, ensure_ascii=False)
        
        # 处理 Markdown 换行符
        assessment = report.get("clinical_assessment", "").replace("\n", "<br>")
        plan = report.get("treatment_recommendations", "").replace("\n", "<br>")

        html_content += f"""
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Patient Case #{sid}</span>
                    {corrected_badge}
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <h5 class="section-title">1. Structured Data (JSON)</h5>
                            <pre><code>{struct_data}</code></pre>
                        </div>
                        <div class="col-md-7">
                            <h5 class="section-title">2. Clinical Assessment (Agent 2)</h5>
                            <div class="assessment-text p-3 border rounded">
                                {assessment}
                            </div>
                            
                            <h5 class="section-title">3. Treatment Recommendations (Agent 3)</h5>
                            <div class="plan-box rounded">
                                {plan}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        """

    html_content += """
        </div>
        <footer class="text-center py-4 text-muted">
            Generated by Gemini Oncology Multi-Agent System © 2026
        </footer>
    </body>
    </html>
    """

    with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"\n[SUCCESS] Dashboard generated: {OUTPUT_HTML}")
    print("Open this file in your browser to view the reports.")

if __name__ == "__main__":
    json_to_html()